from __future__ import annotations

from app.constants.mode import Mode
from app.constants.mods import Mods
from app.constants.score_status import ScoreStatus
from app.models.score import Score
from app.models.stats import Stats
from app.repositories.leaderboards import LeaderboardScore


def make_score(
    *,
    id: int = 1,
    map_md5: str = "a" * 32,
    user_id: int = 1,
    mode: Mode = Mode.STD,
    mods: Mods = Mods(0),
    pp: float = 0.0,
    sr: float = 0.0,
    score: int = 0,
    max_combo: int = 0,
    acc: float = 0.0,
    n300: int = 0,
    n100: int = 0,
    n50: int = 0,
    nmiss: int = 0,
    ngeki: int = 0,
    nkatu: int = 0,
    passed: bool = False,
    quit: bool = False,
    full_combo: bool = False,
    status: ScoreStatus = ScoreStatus.FAILED,
    time: int = 0,
    time_elapsed: int = 0,
    online_checksum: str | None = None,
) -> Score:
    return Score(
        id=id,
        map_md5=map_md5,
        user_id=user_id,
        mode=mode,
        mods=mods,
        pp=pp,
        sr=sr,
        score=score,
        max_combo=max_combo,
        acc=acc,
        n300=n300,
        n100=n100,
        n50=n50,
        nmiss=nmiss,
        ngeki=ngeki,
        nkatu=nkatu,
        passed=passed,
        quit=quit,
        full_combo=full_combo,
        status=status,
        time=time,
        time_elapsed=time_elapsed,
        online_checksum=online_checksum,
    )


def make_stats(
    *,
    user_id: int = 1,
    mode: Mode = Mode.STD,
    ranked_score: int = 0,
    total_score: int = 0,
    pp: float = 0.0,
    rank: int = 0,
    country_rank: int = 0,
    accuracy: float = 0.0,
    playcount: int = 0,
    playtime: int = 0,
    max_combo: int = 0,
    total_hits: int = 0,
    replays_watched: int = 0,
    xh_count: int = 0,
    x_count: int = 0,
    sh_count: int = 0,
    s_count: int = 0,
    a_count: int = 0,
    b_count: int = 0,
    c_count: int = 0,
    d_count: int = 0,
) -> Stats:
    return Stats(
        user_id=user_id,
        mode=mode,
        ranked_score=ranked_score,
        total_score=total_score,
        pp=pp,
        rank=rank,
        country_rank=country_rank,
        accuracy=accuracy,
        playcount=playcount,
        playtime=playtime,
        max_combo=max_combo,
        total_hits=total_hits,
        replays_watched=replays_watched,
        xh_count=xh_count,
        x_count=x_count,
        sh_count=sh_count,
        s_count=s_count,
        a_count=a_count,
        b_count=b_count,
        c_count=c_count,
        d_count=d_count,
    )


def make_leaderboard_score(
    *,
    score_id: int = 1,
    user_id: int = 1,
    score: int = 0,
    max_combo: int = 0,
    full_combo: bool = False,
    mods: int = 0,
    count_300: int = 0,
    count_100: int = 0,
    count_50: int = 0,
    count_geki: int = 0,
    count_katu: int = 0,
    count_miss: int = 0,
    time: int = 0,
    play_mode: int = 0,
    completed: int = 3,
    accuracy: float = 0.0,
    pp: float = 0.0,
    checksum: str | None = None,
    patcher: bool = False,
    pinned: bool = False,
    score_rank: int = 0,
    score_username: str = "test",
) -> LeaderboardScore:
    return LeaderboardScore(
        score_id=score_id,
        user_id=user_id,
        score=score,
        max_combo=max_combo,
        full_combo=full_combo,
        mods=mods,
        count_300=count_300,
        count_100=count_100,
        count_50=count_50,
        count_geki=count_geki,
        count_katu=count_katu,
        count_miss=count_miss,
        time=time,
        play_mode=play_mode,
        completed=completed,
        accuracy=accuracy,
        pp=pp,
        checksum=checksum,
        patcher=patcher,
        pinned=pinned,
        score_rank=score_rank,
        score_username=score_username,
    )


def make_score_tokens(
    *,
    beatmap_md5: str = "a" * 32,
    username: str = "tester",
    online_checksum: str = "c" * 32,
    n300: int = 100,
    n100: int = 0,
    n50: int = 0,
    ngeki: int = 0,
    nkatu: int = 0,
    nmiss: int = 0,
    score: int = 123456,
    max_combo: int = 100,
    full_combo: str = "True",
    grade: str = "S",
    mods: int = 0,
    passed: str = "True",
    mode: int = 0,
) -> list[str]:
    return [
        beatmap_md5,
        username,
        online_checksum,
        str(n300),
        str(n100),
        str(n50),
        str(ngeki),
        str(nkatu),
        str(nmiss),
        str(score),
        str(max_combo),
        full_combo,
        grade,
        str(mods),
        passed,
        str(mode),
    ]
